apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-certificate
spec:
  secretName: bank-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bank.cloudwitches.online
  dnsNames:
    - bank.cloudwitches.online
    - bankapi.cloudwitches.online