apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-certificate
spec:
  secretName: bank-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName:bank.capgrp3banking.online  
  dnsNames:
    -bank.capgrp3banking.online  
    -bankapi.capgrp3banking.online 